/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "AI integration into the editor",
  "description": "Adds AI integration into the editor including code completion, code generation, sprite generation, background generation, and more.",
  "info": [
    {
      "text": "You must have a Gemini API key to use the AI features. To get one, visit https://aistudio.google.com/app/apikey -> new key -> copy the key and paste it into the box below.",
      "id": "warning"
    }
  ],
  "credits": [
    {
      "name": "CodeTorch"
    }
  ],

  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "id": "GeminiAPIKey",
      "name": "Gemini API Key",
      "type": "long_string",
      "default": "",
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
