/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "AI integration into the editor",
  "description": "Adds AI integration into the editor including code completion, code generation, sprite generation, background generation, and more.\n\n\nDISCLAIMER: We do not store any request data or your API keys. Your API keys are only sent with requests and remain fully stored locally on your computer. All models we use are free, ensuring no charges apply. However, for added security, we recommend setting restrictions on your API keys. If you'd like to verify this, our AI backend is open-source—feel free to check it out yourself!",
  "info": [
    {
      "text": "If you need help with creating an API key, check out our guide here: https://blog.codetorch.net/gemini-api-key-for-torchy/",
      "id": "warning"
    }
  ],
  "credits": [
    {
      "name": "CodeTorch"
    }
  ],

  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "id": "GeminiAPIKey",
      "name": "Gemini API Key",
      "type": "long_string",
      "default": "",
    },
    {
      "id": "OpenRouterAPIKey",
      "name": "OpenRouter API Key",
      "type": "long_string",
      "default": "",
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
