/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "AI integration into the editor",
  "description": "Adds AI integration into the editor including code completion, code generation, sprite generation, background generation, and more.",
  "credits": [
    {
      "name": "CodeTorch"
    }
  ],

  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [],
  "enabledByDefault": true
};
export default manifest;
